---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	load_context(load_context)
	search_web(search_web)
	shortlist(shortlist)
	rank_by_cuisine(rank_by_cuisine)
	allocate(allocate)
	ask_clarifications(ask_clarifications)
	write_recipes(write_recipes)
	__end__([<p>__end__</p>]):::last
	__start__ --> load_context;
	allocate -. &nbsp;empty&nbsp; .-> __end__;
	allocate -.-> ask_clarifications;
	allocate -.-> write_recipes;
	load_context --> search_web;
	rank_by_cuisine --> allocate;
	search_web --> shortlist;
	shortlist -. &nbsp;empty&nbsp; .-> __end__;
	shortlist -. &nbsp;rank&nbsp; .-> rank_by_cuisine;
	ask_clarifications --> __end__;
	write_recipes --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
